### ISSUE TITLE
Recoverable alert on OS 3.9 when clicking inbox list

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#382]
**Originally by _72207.463@compuserve.com_ on 2013-01-27 10:12:46 +0100**

___
This problem affects YAM 2.8 on my A3000 with a Cyberstorm MKIII
(68060 @ 50 MHz), running OS 3.9.2. I have installed all of the
latest MUI components used by YAM.

The problem is not repeatable in that there is no consistent
sequence of actions I can perform that will always cause it to
occur. But in normal use of YAM to download and read email it
doesn't take long to happen. The action that seems to trigger it is
clicking on items in the list of emails in the inbox.

The symptom is a recoverable alert with the error code 0100 000C
(MemoryInsane) from the RAM disk task. The alert comes right back
when dismissed, roughly once for each item in the inbox list.
Eventually the alerts end, and YAM resumes working. But clicking
another item in the email list starts the alerts again. Sometimes
the alerts do not end, and keep repeating until I give up and
reboot.

As you might expect given the error, after encountering the problem
the system becomes unstable, and prone to malfunctions or crashing
even when using Workbench or other programs.

I installed the new version of BetterString, but that did not solve
the problem. Running CyberGuard did not show any hits until the
alerts began, after which RAM: crashed before I could capture the
CyberGuard output. The bug has likely occurred some time before
RAM: notices the problem, anyway.

**Comment by tboeckel** [comment]
**Originally on 2013-01-28 09:44:46 +0100**

___
Please get the fixed version of BetterString.mcc from #377 and make sure to set the NList scrollbars to always visible (MUI prefs -> NListviews -> Scrolling). The currently released version of BetterString is known to trash memory and due to a bug in MUI dynamic scrollbars may also cause issues each time the scrollbars are added or removed.

Please report back if these provisions fix this issue.

**Comment by jens-maus** [comment]
**Originally on 2013-01-28 10:17:03 +0100**

___
In addition, please also try to install the latets nightly 2.9-dev build because certain things have been fixed in there already which might also be a reason for the problems you report here.

**Comment by tboeckel** [comment]
**Originally on 2013-01-28 21:23:25 +0100**

___
I just fixed another long standing and memory trashing bug which quite easily might be responsible for this issue. So please try the next nightly build and report back here.

**Comment by jens-maus** [comment]
**Originally by _72207.463@compuserve.com_ on 2013-01-31 08:05:45 +0100**

___
I've already tried the fixed version of BetterString, and that didn't help. I'll give the other suggestions a try, and let you know how it goes.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-01-31 15:34:18 +0100**

___
I get the same error with very similar configuration, it always happens during or right after downloading mail. Usually when filtering but not always. Error code is 0100 000C and the task is called RAM. I tried the scrollbar fix but the problem is still there. Will try with the 2.9-dev build.

**Comment by tboeckel** [comment]
**Originally on 2013-01-31 15:35:56 +0100**

___
Replying to anonymous:

Please remember to log in the next time before you comment on something. This makes communication **MUCH** easier for all involved persons.

**Comment by tboeckel** [comment]
**Originally on 2013-02-06 10:16:34 +0100**

___
Any news on this issue?

**Comment by jens-maus** [comment]
**Originally by _72207.463@compuserve.com_ on 2013-02-07 04:21:38 +0100**

___
I've been using and abusing the 31-Jan dev. build of YAM for almost a week,
and have been unable to reproduce the problem. So I'd say it's been fixed by
one of the changes made since the 2.8 version.

**Comment by jens-maus** [comment]
**Originally by _jostberg_ on 2013-02-07 07:21:04 +0100**

___
I downloaded the 2.9-dev version and the 0100 000C is gone.

**Comment by tboeckel** [comment]
**Originally on 2013-02-07 07:23:01 +0100**

___
Closing this ticket as "invalid" then.
